version: 2.1

jobs:
  build:
    parallelism: 1
    docker:
      - image: cimg/elixir:1.14
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile
      - run: mix format --check-formatted
      - run: mix dialyzer
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"

      - run: MIX_ENV=test mix coveralls.circle

      - store_test_results:
          # Read more: https://circleci.com/docs/2.0/collect-test-data/
          path: _build/test/lib/exconstructor # Replace with the name of your :app

